In [1]:
import pandas as pd
df=pd.read_csv("newdata.csv")
df

,experience,test_score(out of 10),interview_score(out of 10),salary(S)
0,NaN,8.0,9,50000
1,NaN,8.0,6,45000
2,five,6.0,7,60000
3,two,10.0,10,65000
4,seven,9.0,6,70000
5,three,7.0,10,62000
6,ten,NaN,7,72000
7,eleven,7.0,8,80000


In [9]:
df['test_score(out of 10)'].median()

np.float64(8.0)

In [11]:
import math
df.median_test=math.floor(df['test_score(out of 10)'].median())

In [13]:
df.median_test

8

In [34]:
df['test_score(out of 10)']=df['test_score(out of 10)'].fillna(df.median_test)

In [35]:
df

,experience,test_score(out of 10),interview_score(out of 10),salary(S)
0,0,8.0,9,50000
1,0,8.0,6,45000
2,five,6.0,7,60000
3,two,10.0,10,65000
4,seven,9.0,6,70000
5,three,7.0,10,62000
6,ten,8.0,7,72000
7,eleven,7.0,8,80000


In [52]:
df['experience']=df['experience'].astype('string')

In [53]:
from word2number import w2n

df["experience"] = df["experience"].apply(w2n.word_to_num)

In [54]:
df['test_score(out of 10)']=df['test_score(out of 10)'].astype(int)

In [55]:
print(df.dtypes)

experience                    int64
test_score(out of 10)         int64
interview_score(out of 10)    int64
salary(S)                     int64
dtype: object


In [58]:
df

,experience,test_score(out of 10),interview_score(out of 10),salary(S)
0,0,8,9,50000
1,0,8,6,45000
2,5,6,7,60000
3,2,10,10,65000
4,7,9,6,70000
5,3,7,10,62000
6,10,8,7,72000
7,11,7,8,80000


In [57]:
from sklearn import linear_model
reg=linear_model.LinearRegression()

In [60]:
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df[['salary(S)']])

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [63]:
reg.predict([[2,9,6]])

C:\Users\SYED SAIF ALI SHAH\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53205.96797671]])

In [62]:
reg.predict([[12,10,10]])

C:\Users\SYED SAIF ALI SHAH\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[92002.18340611]])

In [65]:
import pandas as pd
d=pd.read_csv('newdata1.csv')
d

,experience,test_score(out of 10),interview_score(out of 10)
0,NaN,8.0,9
1,NaN,8.0,6
2,five,6.0,7
3,two,10.0,10
4,seven,9.0,6
5,three,7.0,10
6,ten,NaN,7
7,eleven,7.0,8


In [66]:
d['experience']=d['experience'].fillna(0)

In [67]:
d

,experience,test_score(out of 10),interview_score(out of 10)
0,0,8.0,9
1,0,8.0,6
2,five,6.0,7
3,two,10.0,10
4,seven,9.0,6
5,three,7.0,10
6,ten,NaN,7
7,eleven,7.0,8


In [69]:
d['experience']=d['experience'].astype('string')


In [75]:
print(d.dtypes)

experience                      int64
test_score(out of 10)         float64
interview_score(out of 10)      int64
dtype: object


In [77]:
median_test1= d['test_score(out of 10)'].median()

In [79]:
d['test_score(out of 10)']=d['test_score(out of 10)'].fillna(median_test1)
d

,experience,test_score(out of 10),interview_score(out of 10)
0,0,8.0,9
1,0,8.0,6
2,5,6.0,7
3,2,10.0,10
4,7,9.0,6
5,3,7.0,10
6,10,8.0,7
7,11,7.0,8


In [81]:
p=reg.predict(d)

In [82]:
p

array([[52350.0727802 ],
       [45734.35225619],
       [58312.95487627],
       [63872.63464338],
       [67270.74235808],
       [61148.47161572],
       [76069.1411936 ],
       [79241.63027656]])

In [87]:
d['salary(S)']=p

In [88]:
d

,experience,test_score(out of 10),interview_score(out of 10),salary(S)
0,0,8.0,9,52350.072780
1,0,8.0,6,45734.352256
2,5,6.0,7,58312.954876
3,2,10.0,10,63872.634643
4,7,9.0,6,67270.742358
5,3,7.0,10,61148.471616
6,10,8.0,7,76069.141194
7,11,7.0,8,79241.630277


In [89]:
df

,experience,test_score(out of 10),interview_score(out of 10),salary(S)
0,0,8,9,50000
1,0,8,6,45000
2,5,6,7,60000
3,2,10,10,65000
4,7,9,6,70000
5,3,7,10,62000
6,10,8,7,72000
7,11,7,8,80000
